version: '3.7'
services:
  localstack:
    network_mode: bridge
    image: localstack/localstack:latest
    container_name: localstack
    environment:
     - SERVICES=s3:4572,ssm:4583,dynamodb:4569,sqs:4568,sns:4570
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4563-4599:4563-4599"
     - "9999:8080"
    volumes:
      - localstack-data:/tmp/localstack
volumes:
  localstack-data:
    name: localstack-data